### ISSUE TITLE
Invalid bucket name

### ISSUE THREAD

**Issue by Mina69** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#21]
I tried to install it using git bash but I faced with this error:

```
$ ./scripts/register.sh --set-default
Creating Execution Role...
Waiting for execution role stack to complete...
Waiting for execution role stack to complete...
Waiting for execution role stack to complete...
Creating Execution Role complete.
./scripts/register.sh: line 70: uuidgen: command not found
Creating temporary S3 Bucket ...
Creating temporary S3 Bucket failed, please try again.
 Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
```

**Comment by Mina69** [comment]
sorry, I must install uuidgen.

**Comment by pranjal-lb** [comment]
**I am getting this error while executing register.sh :**
**Although i have installed the UUID gen** 
An error occurred (ValidationError) when calling the RegisterType operation: 2 validation errors detected: Value 'None' at 'executionRoleArn' failed to satisfy constraint: Member must satisfy
pattern: arn:.+:iam::[0-9]{12}:role/.+; Value 'None' at 'loggingConfig.logRoleArn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:.+:iam::[0-9]{12}:role/.+
