### ISSUE TITLE
Issue with S3 copy

### ISSUE THREAD

**Issue by krisrajzlive** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#27]
I am trying to run the code snippet below:
 "RunCommandTitle": {
            "Type": "AWSUtility::CloudFormation::CommandRunner",
            "DependsOn" : "S3Bucket",
            "Properties": {
                "Command": "aws s3 cp ../LambdaHandler/anomaly_detection.zip s3://krisrajztest/anomaly_detection.zip",
                "Role": "EC2ServerFullAccess"
            }
        }

And getting the error message:
You do not have permissions to make the TerminateInstances API call. Please try again with the necessary permissions.

Can someone help please?

Thanks

**Comment by maslick** [comment]
Same issue here...

**Comment by maslick** [comment]
see issue #24 and a possible remedy #30

**Comment by shantgup** [comment]
Hello,

This is a check in CommandRunner to ensure that instances created can be terminate before they are created. If permissions to terminate instances are not present, every time CommandRunner is created/updated there will be a new EC2 instance that will be billed and will not be terminated unless manually terminated by the user.

We are working on a new major version of CommandRunner, however we will not be removing this check. Instead please ensure that the TerminateInstances API call can be performed.
