### ISSUE TITLE
Improvement: use YAML instead of JSON for the BaseTemplate

### ISSUE THREAD

**Issue by maslick** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#33]
It would be cool if we used YAML for the [BaseTemplate](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner/blob/master/src/main/resources/BaseTemplate.json). Right now I can see there are a couple very long lines, where you can easily make a mistake (in fact there is one [here](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner/blob/master/src/main/resources/BaseTemplate.json#L92)):
<img width="749" alt="Screenshot 2021-10-12 at 14 49 29" src="https://user-images.githubusercontent.com/5644706/136950631-2f6774d1-b8f2-4b4f-a4bd-f702b390d39b.png">

Also the Template looks ugly:
<img width="1128" alt="Screenshot 2021-10-12 at 14 56 51" src="https://user-images.githubusercontent.com/5644706/136951806-d54eff5c-7236-49d0-829f-a0f85bb413f8.png">

**Comment by shantgup** [comment]
The BaseTemplate was originally written in YAML, however there was some trouble using it in the code, so decided to make it JSON instead. I'll take this as an FR as well.
