### ISSUE TITLE
You do not have permissions to make the TerminateInstances API call.  Please try again with the necessary permissions.

### ISSUE THREAD

**Issue by jlongo62** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#38]
Whenever I try to use this, I get this result:

You do not have permissions to make the TerminateInstances API call. 
Please try again with the necessary permissions.

Pull #30 purports to fix this, can you guys create a new release to include it or give us a workaround ?

**Comment by maslick** [comment]
See #24

**Comment by shantgup** [comment]
Hello,

This is a check in CommandRunner to ensure that instances created can be terminate before they are created. If permissions to terminate instances are not present, every time CommandRunner is created/updated there will be a new EC2 instance that will be billed and will not be terminated unless manually terminated by the user.

We are working on a new major version of CommandRunner, however we will not be removing this check. Instead please ensure that the TerminateInstances API call be performed.
