### ISSUE TITLE
Build.sh not working even after changing the instance type

### ISSUE THREAD

**Issue by azhagiripanneerselvam** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#39]
Hi Team, 

I have updated the instance type as suggested in old issue but even after changing the instance type am facing the same issue. 

ERROR

INFO] 67 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.268 s
[INFO] Finished at: 2021-12-19T18:00:53Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project awsutility-cloudformation-commandrunner-handler: Compilation failure: Compilation failure:
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/target/generated-sources/rpdk/software/awsutility/cloudformation/commandrunner/HandlerWrapperExecutable.java:[45,64] wrong number of type arguments; required 2
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/target/generated-sources/rpdk/software/awsutility/cloudformation/commandrunner/HandlerWrapperExecutable.java:[50,54] wrong number of type arguments; required 2
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/target/generated-sources/rpdk/software/awsutility/cloudformation/commandrunner/HandlerWrapperExecutable.java:[54,66] wrong number of type arguments; required 2
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/target/generated-sources/rpdk/software/awsutility/cloudformation/commandrunner/HandlerWrapperExecutable.java:[131,29] wrong number of type arguments; required 2
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/target/generated-sources/rpdk/software/awsutility/cloudformation/commandrunner/HandlerWrapperExecutable.java:[150,43] wrong number of type arguments; required 2
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/target/generated-sources/rpdk/software/awsutility/cloudformation/commandrunner/HandlerWrapper.java:[45,50] wrong number of type arguments; required 2
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/target/generated-sources/rpdk/software/awsutility/cloudformation/commandrunner/HandlerWrapper.java:[50,54] wrong number of type arguments; required 2
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/target/generated-sources/rpdk/software/awsutility/cloudformation/commandrunner/HandlerWrapper.java:[54,66] wrong number of type arguments; required 2
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/target/generated-sources/rpdk/software/awsutility/cloudformation/commandrunner/HandlerWrapper.java:[140,29] wrong number of type arguments; required 2
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/target/generated-sources/rpdk/software/awsutility/cloudformation/commandrunner/HandlerWrapper.java:[159,43] wrong number of type arguments; required 2
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/ReadHandler.java:[26,39] cannot find symbol
[ERROR]   symbol:   method getId()
[ERROR]   location: variable model of type software.awsutility.cloudformation.commandrunner.ResourceModel
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/ReadHandler.java:[31,18] cannot find symbol
[ERROR]   symbol:   method setOutput(java.lang.String)
[ERROR]   location: variable model of type software.awsutility.cloudformation.commandrunner.ResourceModel
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/target/generated-sources/rpdk/software/awsutility/cloudformation/commandrunner/ResourceModel.java:[58,17] cannot find symbol
[ERROR]   symbol: method getId()
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/target/generated-sources/rpdk/software/awsutility/cloudformation/commandrunner/ResourceModel.java:[59,51] cannot find symbol
[ERROR]   symbol: method getId()
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/Configuration.java:[12,9] constructor BaseConfiguration in class software.awsutility.cloudformation.commandrunner.BaseConfiguration cannot be applied to given types;
[ERROR]   required: no arguments
[ERROR]   found: java.lang.String
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/CreateHandler.java:[143,48] cannot find symbol
[ERROR]   symbol:   method getCommand()
[ERROR]   location: variable model of type software.awsutility.cloudformation.commandrunner.ResourceModel
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/CreateHandler.java:[146,26] cannot find symbol
[ERROR]   symbol:   method getRole()
[ERROR]   location: variable model of type software.awsutility.cloudformation.commandrunner.ResourceModel
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/CreateHandler.java:[146,53] cannot find symbol
[ERROR]   symbol:   method getRole()
[ERROR]   location: variable model of type software.awsutility.cloudformation.commandrunner.ResourceModel
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/CreateHandler.java:[149,63] cannot find symbol
[ERROR]   symbol:   method getRole()
[ERROR]   location: variable model of type software.awsutility.cloudformation.commandrunner.ResourceModel
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/CreateHandler.java:[159,26] cannot find symbol
[ERROR]   symbol:   method getLogGroup()
[ERROR]   location: variable model of type software.awsutility.cloudformation.commandrunner.ResourceModel
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/CreateHandler.java:[159,57] cannot find symbol
[ERROR]   symbol:   method getLogGroup()
[ERROR]   location: variable model of type software.awsutility.cloudformation.commandrunner.ResourceModel
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/CreateHandler.java:[162,53] cannot find symbol
[ERROR]   symbol:   method getLogGroup()
[ERROR]   location: variable model of type software.awsutility.cloudformation.commandrunner.ResourceModel
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/CreateHandler.java:[168,27] cannot find symbol
[ERROR]   symbol:   method getSubnetId()
[ERROR]   location: variable model of type software.awsutility.cloudformation.commandrunner.ResourceModel
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/CreateHandler.java:[168,58] cannot find symbol
[ERROR]   symbol:   method getSecurityGroupId()
[ERROR]   location: variable model of type software.awsutility.cloudformation.commandrunner.ResourceModel
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/CreateHandler.java:[169,31] cannot find symbol
[ERROR]   symbol:   method getSubnetId()
[ERROR]   location: variable model of type software.awsutility.cloudformation.commandrunner.ResourceModel
[ERROR] /opt/aws-cloudformation-resource-providers-awsutilities-commandrunner/src/main/java/software/awsutility/cloudformation/commandrunner/CreateHandler.java:[169,60] cannot find symbol
[ERROR]   symbol:   method getSecurityGroupId()

**Comment by shantgup** [comment]
Hello,

To resolve this build error, you will need to ensure that the following are updated.

1. Dependencies in pom.xml
2. Java version
3. cloudformation-cli version

It is working for me using the following versions:

```
cfn --version
cfn 0.2.22

mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/shantgup/Downloads/mvn
Java version: 15.0.2, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
```
