### ISSUE TITLE
CommandRunner not terminating ec2 instances on CloudFormation deployment

### ISSUE THREAD

**Issue by james-gibbons-lark** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#45]
Sometimes the ec2 instances will delete sometimes they won't after a deployment. Has anyone else seen this? We have hundreds of old running ec2 instances I've just noticed

**Comment by shantgup** [comment]
Sorry for the delay in getting back to you.

So CommandRunner will always make the `TerminateInstances` API call, however, many users have SCP policies or tagging-requirements that will deny the API call and the EC2 instance will remain in the account until deleted manually. 

This is the reason why CommandRunner also checks to see if it has permissions for the `TerminateInstances` API call before it even creates the EC2 instance. 

Were you using the new `DisableTerminateInstancesCheck` parameter?

I also recommend that you check CloudTrail's Event History and filter by `EventName: TerminateInstances` and look for the failed API calls made by CommandRunner. This will help you troubleshoot further and figure out why the API calls failed.

Thank you and let me know if you have any questions.
