### ISSUE TITLE
Fixed: Cannot run register.sh in CloudShell

### ISSUE THREAD

**Issue by gitshawn** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#54]
I thought it would be straightforward and a good fit to run `register.sh` in AWS CloudShell but it was not; it was complaining about default region. 

I tried setting `AWS_DEFAULT_REGION` but this did not work...

I dug into `register.sh` and made the region detection more robust, working from CloudShell (no environment var needed) and also tested on my local CLI, and made a PR:

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner/pull/53

**Comment by shantgup** [comment]
Done! Thank you @gitshawn
