### ISSUE TITLE
Multiple Outputs from the command

### ISSUE THREAD

**Issue by Bharath509** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#59]
Hello Everyone,
I'm running a command that gives json object as output
I'm writing that to command-output.txt file

Imagine I wrote {"key1": "value1", "key2": "value2"} to the file

But when I tried to access the output as **!GetAtt Command.Output.a** 
I'm getting below error 

**Requested attribute Output.a does not exist in schema for AWSUtility::CloudFormation::CommandRunner**

But when I wrote **!GetAtt Command.Output**  as output got {\ as output

Please give me a solution where I can access multiple outputs from a command

**Comment by shantgup** [comment]
Hi @Bharath509, you can write your outputs to multiple SSM Parameters, and then reference them in the template using the below format. For more information, see [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-pattern).

```
{{resolve:ssm:ParameterName:1}}
```
